import uiautomator2 as u2

device = u2.connect("38f38fd")
device.screen_on()
device.screen_off()
device.press("home")
device.press("back")
device.press("left")
device.press("right")
device.press("up")
device.press("down")
device.press("center")
device.press("enter")
device.press("camara")
device.press("menu")
device.press("power")
device.press("power")
device.press("search")
device.press("volume_up")
device.press("volume_down")
device.press("volume_mute")
